### ISSUE TITLE
Conda installation issue due to pint version

### ISSUE THREAD

**Issue by rosewangrmi** [Stanford-EAO/OPGEEv4#1]
The yml file for conda installation is not specifying the pint version used. By default, the latest pint version is 0.20, which would throw the following error:
"ERROR: Command errored out with exit status 1:
command: /Users/rwang/opt/anaconda3/envs/opgee/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/rwang/Documents/learn_opgee_python/setup.py'"'"'; file='"'"'/Users/rwang/Documents/learn_opgee_python/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/r5/k5kgh1h937s5kzvhq1gry60r0000gp/T/pip-pip-egg-info-76u1wmhz
cwd: /Users/rwang/Documents/learn_opgee_python/
Complete output (11 lines):
Traceback (most recent call last):
File "", line 1, in
File "/Users/rwang/Documents/learn_opgee_python/setup.py", line 1, in
from opgee.version import VERSION
File "/Users/rwang/Documents/learn_opgee_python/opgee/init.py", line 6, in
import pint_pandas
File "/Users/rwang/opt/anaconda3/envs/opgee/lib/python3.8/site-packages/pint_pandas/init.py", line 3, in
from .pint_array import PintArray, PintType
File "/Users/rwang/opt/anaconda3/envs/opgee/lib/python3.8/site-packages/pint_pandas/pint_array.py", line 21, in
from pint.quantity import _Quantity
ModuleNotFoundError: No module named 'pint.quantity'"
It would be good to specify the same version for pint (0.19.2) in yml document as the requirements.txt file.

@rjplevin @wennanlong

**Comment by rjplevin** [comment]
Thanks for reporting this. I'll take care if it now.

**Comment by rjplevin** [comment]
It turns out that the latest version of pint is incompatible (temporarily) with the latest version of pint_pandas. This is a case of poor release management. I'll update the YML files to force the prior versions for now. This problem will probably be resolved by pint developers within days. (It's already a "closed" issue.)

**Comment by rjplevin** [comment]
I've updated the YML files.
